repaint_delay 10
input_delay 2
sync_to_monitor no

# Make it so Alt-X movements work on macos
macos_option_as_alt left


# BEGIN_KITTY_THEME
# Catppuccin-Macchiato
include current-theme.conf
# END_KITTY_THEME
