# Performance
repaint_delay 10
input_delay 2
sync_to_monitor no

# Font (nerd font required for nvim-web-devicons)
font_family      JetBrainsMono Nerd Font

scrollback_lines 10000

# BEGIN_KITTY_THEME
# Catppuccin-Macchiato
include current-theme.conf
# END_KITTY_THEME


# [!] MacOS only
# Comment out this block on linux.

# Bash as default shell
shell /opt/homebrew/bin/bash

# kitty doesn't send Alt by default. Needed for <A-t>, <A-h> etc in nvim.
# Use `left` instead of `yes` to keep right-Option for accented chars.
macos_option_as_alt left

macos_quit_when_last_window_closed yes
macos_titlebar_color background
confirm_os_window_close 0
